### ISSUE TITLE
Error: 'no such object path /dolphin/Dolphin_1'

### ISSUE THREAD

**Issue by slynobody** [Nyre221/Kiview#13]
thank you for your help on the other issue.

i compiled both versions now. and while the latest (as you mentioned) does not support dolphin currently, the older one should, right? i did not get the keyboard-keystroke working, but installed the dolphin-addon. when activating the dolphin-add through right click menu, an window opens saying 'no such object path /dolphin/Dolphin_1'?

**Comment by Nyre221** [comment]
Do you have Klipper enabled?
The version on github, the only one with the integration, uses a hack to work:
https://github.com/Nyre221/Kiview/issues/7

hmm, I know the dolphin developers wanted to block the hack I used to get it working, I don't know if they've done that yet.

What distribution do you have?
type: ` dolphin --version`

keep in mind that it needs qdbus to work, so check if your distro or you have disabled something.

**Comment by slynobody** [comment]
terribly sorry, after a restart it worked. great.
hopefully your application on invent will become mature soon – and will be integrated into plasma soon.

btw: do you know a simple way to get a simple keystroke like just the spacebar to work (in dolphin only)? and is the github-version i am currently working with again immune against injections like https://github.com/Nyre221/Kiview/issues/5?

**Comment by Nyre221** [comment]
> btw: do you know a simple way to get a simple keystroke like just the spacebar to work (in dolphin only)?

only on dolphin it is not "possible", not cleanly at least.

In theory, you could create a script that checks if the active window is dolphin (If you use xorg you can try xdotool), and launches Kiview if it is. Then you use something to create a shortcut for your script and have it run when you press the `space` key.

In dolphin you have to remove the shortcut for the selection mode:

![Schermata_20240813_191319](https://github.com/user-attachments/assets/da321a20-c486-4675-ae62-47e9a73c2320)

> is the github-version i am currently working with again immune against injections

This was fixed shortly after the first release of kiview on flathub. No version is breakable with that command.

However, the trick it uses to work with dolphin uses `bash` in one section. I tried to break it and failed, so it seems much more robust. If you want to be more safe, use the flatpak version  (can't delete or overwrite stuff)  or uninstall `xclip` and `wl-clipboard` .
Edit:    
////
to clarify, the version where the command injection was fixed, checks for some special characters and avoids using `bash` to restore if it finds them. this was done to prevent it from being vulnerable to other malicious strings.
////
Note: if you uninstall `xclip` and `wl-clipboard`, the contents of the clipboard will be restored as plain text, and thus a previously copied file will not be "pastable".

**Comment by Nyre221** [comment]
@slynobody 

Just in case you're interested:
https://github.com/Nyre221/dolphin-quick-view/blob/main/package%20creation/quick_view_package/dolphin_quick_view_shortcut.sh

If you want you can use the Quick View script (Kivew in python) to use the new version of kiview.

in the last line you have to change the command and the position of the arguments:   
From:
`~/.config/quick_view/quick_view.pyz "$path" $parameter`
To:   
`kiview  $parameter "$path" `


Not tried , but it should work. 

The latest version of kiview is even more robust to command ignition since there is less use of `bash`.
Of course the script in bash can be vulnerable. 

If you are capable you can rewrite it in python or reintegrate dolphinbridge.cpp (not present in the latest version of kiview).

https://invent.kde.org/danagost/Kiview/-/merge_requests/7

**Comment by slynobody** [comment]
great, thank you! 

works. altering https://github.com/Nyre221/dolphin-quick-view/blob/main/package%20creation/quick_view_package/dolphin_quick_view_shortcut.sh in the way mentioned worked. 

why does it have the lag from pressing shortcut to opening? 
would be nice to know how to create a simple one-line-package for the kde-shortcut (like the dolphin-plugin) to also make this automatic.

**Comment by Nyre221** [comment]
@slynobody 
> why does it have the lag from pressing shortcut to opening?

Two reasons:
1) dbus sometimes fails if the command is repeated/re-executed too fast.
2) since it sends  to dolphin the signal to select all files and copy the location, the script must give dolphin time to do these actions:


```
#sends the signal to dolphin to copy the location of the current file to the clipboard.
dbus-send --session --print-reply --type=method_call --dest=$dolphin /dolphin/Dolphin_1/actions/copy_location org.qtproject.Qt.QAction.trigger
[ "$?" != "0" ] && restore_clipboard_content "$original_clipboard_content" && exit 1

sleep 0.1
#gets clipboard contents from klipper
path="$(dbus-send --session --print-reply --type=method_call --dest=org.kde.klipper /klipper org.kde.klipper.klipper.getClipboardContents | grep string | cut -d'"' -f2)"
[ "$?" != "0" ] && restore_clipboard_content "$original_clipboard_content" && exit 1

```


```
if [ ! -e "$path" ]; then
dbus-send --session --print-reply --type=method_call --dest=$dolphin /dolphin/Dolphin_1/actions/edit_select_all org.qtproject.Qt.QAction.trigger
[ "$?" != "0" ] && restore_clipboard_content "$original_clipboard_content" && exit 1
sleep 0.1
#enables copying the file path even if multiple files are selected (plasma 6)
dbus-send --session --print-reply --type=method_call --dest=$dolphin /dolphin/Dolphin_1/actions/copy_location org.qtproject.Qt.QAction.resetEnabled
#gets file location
dbus-send --session --print-reply --type=method_call --dest=$dolphin /dolphin/Dolphin_1/actions/copy_location org.qtproject.Qt.QAction.trigger
[ "$?" != "0" ] && restore_clipboard_content "$original_clipboard_content" && exit 1
sleep 0.1
path=$(dbus-send --session --print-reply --type=method_call --dest=org.kde.klipper /klipper org.kde.klipper.klipper.getClipboardContents | grep string | cut -d'"' -f2)
[ "$?" != "0" ] && restore_clipboard_content "$original_clipboard_content" && exit 1
#deselect what was previously selected (aesthetic reason)
dbus-send --session --print-reply --type=method_call --dest=$dolphin /dolphin/Dolphin_1/actions/invert_selection org.qtproject.Qt.QAction.trigger
[ "$?" != "0" ] && restore_clipboard_content "$original_clipboard_content" && exit 1
```
you can decrease or remove the waiting times if your pc is fast enough.

The c++ version is much better written and faster, and not only because it is in C++.


> would be nice to know how to create a simple one-line-package for the kde-shortcut (like the dolphin-plugin) to also make this automatic.

I'm not sure I understand what you mean, but in any case this hack will be blocked/mitigated in dolphin in future releases and will no longer be usable.

**Comment by slynobody** [comment]
great, thanks for the information. hope it will get into plasma soon. any timeschedules for this?

**Comment by Nyre221** [comment]
@slynobody 

> great, thanks for the information. hope it will get into plasma soon. any timeschedules for this?

I'm not sure at the moment, but I'm guessing five or six months (probably less).

There isn't much left to do on the programming side (finishing the integration with Dolphin, cleaning up the code, etc), but KDE has a process by which applications become officially part of KDE and I don't know how long that takes.

If there are no unexpected problems, I think I can finish writing the code in 2 months or less.

Keep in mind that Kiview still has to go through the active/review phase, so it's hard to tell you how much more time is needed.

https://develop.kde.org/docs/getting-started/add-project/ 

On top of all this, there is also this bug that could slow down the process: https://bugreports.qt.io/browse/QTBUG-130386
