### ISSUE TITLE
[HELP] How to assign Dolphin shortcut to KiView?

### ISSUE THREAD

**Issue by abbasou** [Nyre221/Kiview#14]
First, I want to say thank you for this. It's the closest I've found to a QuickLook equivalent for KDE (on Fedora 40). My question is whether there is a way to assign a shortcut in Dolphin (i.e. `Space`) to finish the transition? I set up the KDE shortcut, but it seems preferable to have a Dolphin-specific shortcut rather than system-wide.

**Comment by Nyre221** [comment]
@abbasou 

> I set up the KDE shortcut, but it seems preferable to have a Dolphin-specific shortcut rather than system-wide.

The public version of Kiview integrates with dolphin via a hack and there is no other way at the moment.

A new version of kiview, which will become an official KDE application, is in the works and will integrate with dolphin without using hacks/tricks.

https://invent.kde.org/danagost/Kiview

It is still in the incubation phase and it is not possible to use it right now (there is no integration with dolphin at the moment).    

When it is ready I suppose it will be distributed automatically with the new versions of dolphin

Thanks for your interest, have a nice day
