### ISSUE TITLE
custom shortcut to close the app

### ISSUE THREAD

**Issue by Ramen-LadyHKG** [Nyre221/Kiview#15]
Since `Space` is not allowed to assign in KDE `System Settings`.

I have to assign `Ctrl+Space` or `Alt+Space`.

but the default `Kiview` shortcut to close the app is `Space` or `Esc`

would be nice to also close the app with `Alt+Space`

**Comment by Nyre221** [comment]
@Ramen-LadyHKG 

Hi, thanks for your interest.

This is the old, and so far only, working version of kiview.   
A new version is in development and will be integrated directly into dolphin with the ability to change the shortcut to `space` for opening kiview.

Maybe in the future the ability to change kiview's internal shortcuts will be added, but this is not one of the goals at the moment.
