### ISSUE TITLE
Fedora 39 KDE Spin build issues

### ISSUE THREAD

**Issue by RedBearAK** [Nyre221/Kiview#2]
@Nyre221 

The flatpak-builder stage of the install instructions failed on Fedora 39 KDE Spin. I can't copy all the text from the VM, but I'll summarize the errors that are being displayed: 

```sh
com.nyre.kiview
    E: icon-not-found

general
    E: filters-but-no-outut
```

This is just after a line saying "Composing metadata...". 

The "flatpak run" command says the app is not installed after the build failure, and the Kiview app doesn't appear in the app launcher menu. 

This is a normal Plasma 5 setup, not like the other issue with Plasma 6 on Neon, which is based on Ubuntu 22.04 LTS as far as I know. Reason for the build failure happening here on Fedora 39 but not on Neon is unknown.

**Comment by Nyre221** [comment]
8384707
